Updated redis from 3.1.2 to 4
ministryofjustice/hmpps-manage-adjudications pull request #1206
Opened 2024-12-13 11:11 UTC by cugorji-justice

https://dsdmoj.atlassian.net/browse/NN-5989

2024-12-17 12:55 UTC, andrewrlee commented on server/data/tokenStore.ts
> +    return (await this.client).get(key)
think there shouldn't be an await on the client its self

`await this.client.get(key)`
`await this.client.set(key, token, { EX: durationSeconds })

2024-12-17 13:02 UTC, andrewrlee commented on server/data/redisClient.ts
> +  client.connect().catch((e: Error) => logger.error('Failed to connect to Redis', e))
maybe do this in the setUpWebSession [like in the template project](https://github.com/ministryofjustice/hmpps-template-typescript/blob/576409caf776c876219b897c715dc329ca30add4/server/middleware/setUpWebSession.ts#L13)

2024-12-17 13:04 UTC, andrewrlee commented on .circleci/config.yml
> +#          command: npx wait-on http://localhost:3007
You can use the command from the helm orb https://github.com/ministryofjustice/offender-categorisation/blob/475a15f6e9ad0c237c8ad413fd8b73c8a913ffd9/.circleci/config.yml#L127-L129

2024-12-17 18:00 UTC, andrewrlee commented on server/data/tokenStore.ts
> +    this.client.set(this.prefix + key, token, { EX: durationSeconds })
ooh, if you don't want to await it then you'd need to return this promise.

2024-12-18 10:53 UTC, theDustRoom requested changes
Just a minor change, all looks really good.

2024-12-18 10:53 UTC, theDustRoom commented on .circleci/config.yml
> +#      - run:
Can you remove the commented code as it's now redundant?

2024-12-18 13:03 UTC, theDustRoom approved these changes
Nice work Chux

2024-12-18 13:03 UTC, merged